apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product
    version: 1.2.4
    environment: production-env
  annotations:
    description: This application belongs to the product team
    contact: Contact head of profuct for information
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80