apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    key1: value-1
    key2: value-2
    key3: value-3
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80